-- DOLE Portal profile avatars and server-side inactivity sessions
-- Run once in Supabase SQL Editor before using Settings or the 2-hour timeout.

alter table public.users
    add column if not exists avatar_url text null;

alter table public.gips
    add column if not exists avatar_url text null;

create table if not exists public.portal_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    last_activity_at timestamptz not null default now(),
    revoked_at timestamptz null,
    created_at timestamptz not null default now()
);

alter table public.portal_sessions
    add column if not exists last_activity_at timestamptz;

update public.portal_sessions
set last_activity_at = coalesce(last_activity_at, created_at, now())
where last_activity_at is null;

alter table public.portal_sessions
    alter column last_activity_at set default now();

create index if not exists portal_sessions_token_idx
    on public.portal_sessions using btree (token_hash)
    where revoked_at is null;

create index if not exists portal_sessions_activity_idx
    on public.portal_sessions using btree (last_activity_at desc)
    where revoked_at is null;

create index if not exists portal_sessions_expiry_idx
    on public.portal_sessions using btree (expires_at)
    where revoked_at is null;

-- The API uses the service-role client for portal_sessions. Keep this table
-- unavailable to the browser client even if a broad policy is added later.
alter table public.portal_sessions enable row level security;