/**
 * DOLE Iligan Portal — Tickets API
 * CRUD operations for the tickets table.
 * Used by: ticket-support.js (Admin ticket inbox and management)
 *
 * Ticket lifecycle:
 *  Created → status: 'Pending'
 *  Opened/Viewed → status: 'Open'
 *  Resolved → status: 'Closed'
 */

import { supabase } from './supabase.js';

/**
 * Fetch all active tickets with category join.
 * @param {object} filters  — { category_id, priority, status, search }
 * @returns {{ data: Array, error: string|null }}
 */
export async function fetchTickets(filters = {}) {
    let query = supabase
        .from('tickets')
        .select(`
            id,
            ticket_number,
            subject,
            priority,
            status,
            team,
            tags,
            unread_count,
            last_activity,
            created_at,
            updated_at,
            created_by,
            category_id,
            ticket_categories ( name, icon ),
            users!tickets_created_by_fkey ( full_name, username, email )
        `)
        .is('archived_at', null)
        .order('created_at', { ascending: false });

    if (filters.category_id) {
        query = query.eq('category_id', filters.category_id);
    }
    if (filters.priority && filters.priority !== 'All') {
        query = query.eq('priority', filters.priority);
    }
    if (filters.status && filters.status !== 'All') {
        query = query.eq('status', filters.status);
    }

    const { data, error } = await query;

    if (error) {
        if (window.DEBUG) window.DEBUG.error('TICKETS-API', 'Failed to fetch tickets', error.message);
        return { data: [], error: error.message };
    }
    return { data: data || [], error: null };
}

/**
 * Fetch a single ticket by its ticket_number (e.g., 'TK-0001').
 * @param {string} ticketNumber
 * @returns {{ data: object|null, error: string|null }}
 */
export async function fetchTicketByNumber(ticketNumber) {
    const { data, error } = await supabase
        .from('tickets')
        .select(`
            id, ticket_number, subject, priority, status, team, tags,
            unread_count, last_activity, created_at, updated_at, category_id,
            ticket_categories ( name, icon ),
            users!tickets_created_by_fkey ( full_name, username, email )
        `)
        .eq('ticket_number', ticketNumber)
        .single();

    if (error) return { data: null, error: error.message };
    return { data, error: null };
}

/**
 * Create a new ticket.
 * New tickets are always created with status: 'Pending' (changed to 'Open' when viewed).
 * ticket_number is auto-generated by the DB trigger (TK-0001 format).
 *
 * @param {object} payload  — { created_by, category_id, subject, priority, team, tags }
 * @returns {{ data: object|null, error: string|null }}
 */
export async function createTicket(payload) {
    const newTicket = {
        ...payload,
        status: 'Pending',
        unread_count: 1,
        last_activity: new Date().toISOString(),
    };

    const { data, error } = await supabase
        .from('tickets')
        .insert([newTicket])
        .select()
        .single();

    if (error) {
        if (window.DEBUG) window.DEBUG.error('TICKETS-API', 'Create ticket failed', error.message);
        return { data: null, error: error.message };
    }
    if (window.DEBUG) window.DEBUG.success('TICKETS-API', `Ticket created: ${data.ticket_number}`);
    return { data, error: null };
}

/**
 * Open a ticket — sets status to 'Open' and clears unread count.
 * Called when admin clicks/opens a ticket from the inbox.
 * @param {number} ticketId
 * @returns {{ error: string|null }}
 */
export async function openTicket(ticketId) {
    const { error } = await supabase
        .from('tickets')
        .update({
            status: 'Open',
            unread_count: 0,
            updated_at: new Date().toISOString(),
        })
        .eq('id', ticketId);

    if (error) return { error: error.message };
    return { error: null };
}

/**
 * Update ticket fields (priority, status, subject, team, tags, category).
 * @param {number} ticketId
 * @param {object} updates
 * @returns {{ data: object|null, error: string|null }}
 */
export async function updateTicket(ticketId, updates) {
    const { data, error } = await supabase
        .from('tickets')
        .update({ ...updates, updated_at: new Date().toISOString() })
        .eq('id', ticketId)
        .select()
        .single();

    if (error) {
        if (window.DEBUG) window.DEBUG.error('TICKETS-API', `Update ticket ${ticketId} failed`, error.message);
        return { data: null, error: error.message };
    }
    return { data, error: null };
}

/**
 * Close a ticket — sets status to 'Closed'.
 * @param {number} ticketId
 * @returns {{ error: string|null }}
 */
export async function closeTicket(ticketId) {
    const { error } = await supabase
        .from('tickets')
        .update({ status: 'Closed', updated_at: new Date().toISOString() })
        .eq('id', ticketId);

    if (error) return { error: error.message };
    return { error: null };
}

/**
 * Archive (soft-delete) a ticket.
 * @param {number} ticketId
 * @returns {{ error: string|null }}
 */
export async function archiveTicket(ticketId) {
    const { error } = await supabase
        .from('tickets')
        .update({ archived_at: new Date().toISOString() })
        .eq('id', ticketId);

    if (error) return { error: error.message };
    return { error: null };
}

/**
 * Get ticket category counts for the sidebar badges.
 * @returns {{ data: object, error: string|null }}
 *  data = { All: N, 'Support Requests': N, 'Bug Report': N, 'Feature Request': N }
 */
export async function fetchTicketCategoryCounts() {
    const { data, error } = await supabase
        .from('tickets')
        .select('category_id, ticket_categories ( name )')
        .is('archived_at', null);

    if (error) return { data: {}, error: error.message };

    const counts = { All: data.length };
    data.forEach(ticket => {
        const catName = ticket.ticket_categories?.name || 'Unknown';
        counts[catName] = (counts[catName] || 0) + 1;
    });

    return { data: counts, error: null };
}

/**
 * Fetch all ticket categories for filter dropdowns.
 * @returns {{ data: Array, error: string|null }}
 */
export async function fetchTicketCategories() {
    const { data, error } = await supabase
        .from('ticket_categories')
        .select('*')
        .order('id');

    if (error) return { data: [], error: error.message };
    return { data: data || [], error: null };
}

/**
 * Fetch tickets belonging to a specific user (staff/HR role-based view).
 * Staff and HR users can only see tickets they created themselves.
 * @param {number} userId  — The ID of the logged-in staff/HR user
 * @param {object} filters — { category_id, priority, status }
 * @returns {{ data: Array, error: string|null }}
 */
export async function fetchTicketsByUser(userId, filters = {}) {
    let query = supabase
        .from('tickets')
        .select(`
            id,
            ticket_number,
            subject,
            priority,
            status,
            team,
            tags,
            unread_count,
            last_activity,
            created_at,
            updated_at,
            created_by,
            category_id,
            ticket_categories ( name, icon ),
            users!tickets_created_by_fkey ( full_name, username, email )
        `)
        .is('archived_at', null)
        .eq('created_by', userId)
        .order('created_at', { ascending: false });

    if (filters.category_id) {
        query = query.eq('category_id', filters.category_id);
    }
    if (filters.priority && filters.priority !== 'All') {
        query = query.eq('priority', filters.priority);
    }
    if (filters.status && filters.status !== 'All') {
        query = query.eq('status', filters.status);
    }

    const { data, error } = await query;

    if (error) {
        if (window.DEBUG) window.DEBUG.error('TICKETS-API', `Failed to fetch tickets for user ${userId}`, error.message);
        return { data: [], error: error.message };
    }
    return { data: data || [], error: null };
}

